# Generated by Django 5.0 on 2023-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_category_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
